import ProjectPage from "../components/ProjectPage";
export default function Strudel() {
  const songURLs = [
    "https://strudel.cc/#Ly8gQHRpdGxlIE9jYXJpbmEgQmVhdAovLyBAYnkgSmFjb2IgRmVpdCBNYW5uCgoKY29uc3Qgb2NhcmluYSA9ICBuKCI8MiBbLSAxXSAtIFs8MyAtID4gIDw0IDUgNj5dID4qNCIuYWRkKDApKS5zY2FsZSgiRjptYWpvciIpLnNvdW5kKCJvY2FyaW5hIikKICAuYWRzcigiLjA1Oi40Oi43Oi42IikKICAucm9vbSgwLjMpLmRlbGF5KCIwLjg6MC42OjAuNiIpCmNvbnN0IGd1aXRhciA9ICBuKCI8MiBbLSAxXSAtIFs8MyAtID4gIDw0IDUgNj5dID4qNCIuYWRkKDApKS5zY2FsZSgiRjptYWpvciIpLnNvdW5kKCJnbV9lbGVjdHJpY19ndWl0YXJfamF6ejo4IikKICAuYXR0YWNrKDAuMDUpLmRlY2F5KDAuMSkuc3VzdGFpbigwLjMpLnJlbGVhc2UoMC42KQogIC5oYXJkKCI0Oi4wNiIpCiAgLnJvb20oIjAuNzo0IikuZGVsYXkoIjAuNDowLjQ6MC4yIikKY29uc3QgcmVlc2UgPSBub3RlKCI8W2YxIGExXSBbYzFAMyBlMV0%2BLzIiKS5zb3VuZCgiZ21fc3ludGhfYnJhc3NfMSIpCmNvbnN0IGtpY2tTbmFyZSA9IHMoIjxiZCBzZD4qMiIpLmJhbmsoImJvc3NkcjExMCIpLnJvb20oIjAuMjowLjMiKQpjb25zdCBoYXRzID0gcygiaGgqMiBbaGggaGggaGhdIGhoKjIgPGhoIFtoaCBbaGggaGhdXT4iKS5iYW5rKCJib3NzZHIxMTAiKS5nYWluKDAuMikucm9vbSgiMC4xOjAuMSIpCmNvbnN0IHJpbSA9IHMoIi0gLSA8IC0gcmltID4iKS5iYW5rKCJhbGVzaXNzcjE2IikuZ2FpbigwLjQpCmNvbnN0IGRydW1zID0gc3RhY2soa2lja1NuYXJlLCBoYXRzLCByaW0pCgokOiBzdGFjaygKICBhcnJhbmdlKFsxNiwgb2NhcmluYV0pLAogIGFycmFuZ2UoWzgsIHNpbGVuY2VdLCBbOCwgcmVlc2VdKSwKICBhcnJhbmdlKFs4LCBzaWxlbmNlXSwgWzgsIGRydW1zXSwgWzQsIHNpbGVuY2VdLCBbMTIsIGtpY2tTbmFyZV0pLAogIGFycmFuZ2UoWzQsIHNpbGVuY2VdLCBbNCwgZ3VpdGFyXSksCikuX3BpYW5vcm9sbCgp",
    "https://strudel.cc/#Ly8gQHRpdGxlIEEgTW9vZHkgU29uZwovLyBAYnkgSmFjb2IgRmVpdCBNYW5uCgpjb25zdCBzYXggPSBub3RlKCI8YSNAMiBbIGEgZiBdIC0gZyBlIGcgZD4qNCwgZiBhIGQgZSIpCiAgICAgICAgLnNvdW5kKCJzYXhfc3RhY2MiKS5kZWxheSgiMC40OjEvMyIpCiAgICAgICAgLmxwZigiWyAzMDBAMyA2MDAqMyAxMDAwIDIwMDAgXS8yIikKICAgICAgICAuY29sb3IoInRlYWwiKQpjb25zdCB0cmlhbmdsZUhpdCA9IHNvdW5kKCJ0cmlhbmdsZXMvMiIpLmdhaW4oMTgpLmRlbGF5KCIwLjU6MS80IikucmVwbGljYXRlKDIpLmNvbG9yKCJ5ZWxsb3ciKQoKY29uc3QgcGlhbm8gPSBzdGFjaygKICAgICAgICAiYTIgZzIiLAogICAgICAgICJjMiBhIzIiLAogICAgICAgICJlMyBmIiwKICAgICAgICAiZzQgYTQiLm9mZigxLzE2LCB4PT54LmFkZCg3KSksCikuY29sb3IoImdyZWVuIikuc2xvdygyKS5ub3RlKCkuc291bmQoInBpYW5vIikuZGVsYXkoIjAuNjoxLzEyIikKY29uc3Qga2ljayA9IHMoIjxiZCBbYmQgLSAtIGJkIF0%2BIDwtIFsgLSBiZF0%2BIikuY29sb3IoInB1cnBsZSIpLmJhbmsoImFsZXNpc2hyMTYiKQpjb25zdCBoYXRzID0gcygiaGghNCAtIGhoITMiKS5jb2xvcigid2hpdGUiKS5iYW5rKCJkcjIyMCIpLmdhaW4oIjwwLjE4QDMgMC4zPio4IikucGFuKCJbIDAuOCAwLjIgXSoyIikubHBmKDEwMDAwKQpjb25zdCBwZXJjTG9vcCA9IG4oIjwgMSA8MiAyKjI%2BIDQgMyA%2BKjgiKS5jb2xvcigib3JhbmdlIikucygicGVyYyIpLmJhbmsoImFsZXNpc2hyMTYiKS5nYWluKDAuMikucGFuKCI8IDAuMSAwLjkgPioyIikKCiQ6IHN0YWNrKAogICAgICAgIGFycmFuZ2UoWzE2LCBzYXhdKSwKICAgICAgICBhcnJhbmdlKFs0LCBzaWxlbmNlXSwgWzI4LCB0cmlhbmdsZUhpdF0sIFs4LCBzaWxlbmNlXSwgWzE2LCB0cmlhbmdsZUhpdF0pLAogICAgICAgIGFycmFuZ2UoWzgsIHNpbGVuY2VdLCBbOCwgcGlhbm9dLCBbMiwgc2lsZW5jZV0sIFsxNCwgcGlhbm9dKSwKICAgICAgICBhcnJhbmdlKFsxNiwgc2lsZW5jZV0sIFsxNiwga2lja10pLAogICAgICAgIGFycmFuZ2UoWzE2LCBzaWxlbmNlXSwgWzE2LCBoYXRzXSwgWzE2LCBzaWxlbmNlXSwgWzEyLCBoYXRzXSksCiAgICAgICAgYXJyYW5nZShbMjQsIHNpbGVuY2VdLCBbOCwgcGVyY0xvb3BdKSwKKS5wdW5jaGNhcmQoe2xhYmVsczogMX0p",
  ];
  return (
    <ProjectPage title="Strudel Compositions">
      <p>
        Some experiments in coding music using{" "}
        <a href="https://strudel.cc/workshop/getting-started/" target="_blank">
          Strudel
        </a>
        .
      </p>
      <div className="grid grid-col w-full gap-2">
        {songURLs.map((song) => (
          <iframe
            className="w-full min-h-70 border-2 border-primary"
            src={song}
          ></iframe>
        ))}
      </div>
    </ProjectPage>
  );
}
